### ISSUE TITLE
Este archivo expone los app key y secret de la app

### ISSUE THREAD

**Issue by acrosa** [KCHETO/iOS#10]
Habra que o hacer este repo privado o removerlos del proyecto. (Si podes por favor regenera las keys porque seguro ya las chorearon :))
https://github.com/KCHETO/iOS/blob/master/KCHETO/Info.plist

**Comment by martinblech** [comment]
En el slack de NSCoder BA me recomendaron esto hace un tiempo: https://github.com/orta/cocoapods-keys
Lo probamos?

**Comment by nicopuri** [comment]
Genial @martinblech, le pego una mirada!

Es verdad eso de las Keys pero es un repo privado. Pero cualquiera que se baje el proyecto puede saber las Keys asi que las regenero y trato de meterlas en otro lado.
